# ==============================================================================
# STEP 10: DEPLOY ORDERS MICROSERVICE
# ==============================================================================
# 
# What is this?
# - Your Orders API microservice
# - Manages customer orders
# - Communicates with Products and Users services
# 
# ==============================================================================

---
# Orders App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-app
  namespace: microservices-poc
  labels:
    app: orders-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-app
  template:
    metadata:
      labels:
        app: orders-app
        tier: backend
    spec:
      containers:
      - name: orders-app
        image: ravishchauhan/orders-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3

---
# Orders App Service
apiVersion: v1
kind: Service
metadata:
  name: orders-app
  namespace: microservices-poc
  labels:
    app: orders-app
spec:
  selector:
    app: orders-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

# ==============================================================================
# How to apply this file:
#   kubectl apply -f step10-orders-app.yaml
#
# How to verify:
#   kubectl get deployment orders-app -n microservices-poc
#   kubectl get pods -l app=orders-app -n microservices-poc
#   kubectl logs -f deployment/orders-app -n microservices-poc
#
# Check all three microservices:
#   kubectl get pods -l tier=backend -n microservices-poc
#   Should see 6 pods total (2 for each service)
# ==============================================================================
