# ==============================================================================
# STEP 9: DEPLOY USERS MICROSERVICE
# ==============================================================================
# 
# What is this?
# - Your Users API microservice
# - Manages user accounts, authentication, profiles
# - Similar structure to Products service
# 
# ==============================================================================

---
# Users App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app                           # Name: user-app (matches your docker-compose)
  namespace: microservices-poc
  labels:
    app: user-app
    tier: backend
spec:
  replicas: 2                              # 2 instances for reliability
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
        tier: backend
    spec:
      containers:
      - name: user-app
        image: ravishchauhan/user-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3

---
# Users App Service
apiVersion: v1
kind: Service
metadata:
  name: user-app                           # Service name
  namespace: microservices-poc
  labels:
    app: user-app
spec:
  selector:
    app: user-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP

# ==============================================================================
# How to apply this file:
#   kubectl apply -f step9-users-app.yaml
#
# How to verify:
#   kubectl get deployment user-app -n microservices-poc
#   kubectl get pods -l app=user-app -n microservices-poc
#   kubectl logs -f deployment/user-app -n microservices-poc
#
# Test the service:
#   kubectl port-forward -n microservices-poc service/user-app 8081:8080
#   curl http://localhost:8081/health
# ==============================================================================
